### ISSUE TITLE
Issue with knife-vsphere 0.9.8 and chef 11.4.4?

### ISSUE THREAD

**Issue by hinder90** [ezrapagel/knife-vsphere#90]
Since the update of the knife-vsphere from 0.9.7 to 0.9.8 (on my chef 11.4.4 installation on ubuntu) this problem occurs whenever I try to run knife at all:

builder@w1-sc-chef-dev-02:~$ knife help
/usr/lib/ruby/gems/1.9.1/gems/knife-vsphere-0.9.8/lib/chef/knife/vsphere_datastorecluster_maxfree.rb:30:in `<class:VsphereDatastoreclusterMaxfree>': undefined method `[]=' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby/gems/1.9.1/gems/knife-vsphere-0.9.8/lib/chef/knife/vsphere_datastorecluster_maxfree.rb:22:in `<top (required)>'
	from /usr/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/knife/core/subcommand_loader.rb:37:in `load'
	from /usr/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/knife/core/subcommand_loader.rb:37:in `block in load_commands'
	from /usr/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/knife/core/subcommand_loader.rb:37:in `each'
	from /usr/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/knife/core/subcommand_loader.rb:37:in `load_commands'
	from /usr/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/knife.rb:119:in `load_commands'
	from /usr/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/knife.rb:167:in `run'
	from /usr/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/application/knife.rb:123:in `run'
	from /usr/lib/ruby/gems/1.9.1/gems/chef-11.4.4/bin/knife:25:in `<top (required)>'
	from /usr/bin/knife:23:in `load'
	from /usr/bin/knife:23:in `<main>'

**Comment by swalberg** [comment]
This seems to be resolved... I'm trying to clean up old issues, so I'll close this. If you have any further problems, can you open up a new issue please?
